### ISSUE TITLE
The AXP2021 chip shutdown by itself

### ISSUE THREAD

**Issue by VovaN60** [lewisxhe/XPowersLib#6]
Hello Dear,

May be this issue is not related to the library.
But i have no any other support sources.

The new boards arrived. All 50 are having strange behavier.
It is eather electrical connection issue or AXP2101 are faulty.

I am receiving this IRQ's in a raw and after that MPU shutdown:
**isVbusRemove 
isBatInsert 
isBatRemove 
isPekeyShortPress 
isPekeyLongPress**

This issue can happen during charging or during normal operations.
This issue can happen 1 hour after start or even 40 hours after start.
And i can not find any links to anything. It is just random shutdowns...

I am using 
DCDC1 as ESP32 + Radio module power supply (max 0.6A total)
DCDC3 as GPS power supply (max 0.3A)
ALDO1 as gyro power supply (little load)
ALDO2 as spare power supply.

Kindly help with your expirience.

**Comment by lewisxhe** [comment]
First of all, I can be sure that it is normal to interrupt the writing of this library, because several projects have already used it, so I will search from these two aspects based on my personal experience
1. Is the AXP2101 hardware connection normal? I am referring to VBUS, VBAT, IRQ, SDA, SCL, which are important circuits that are prone to IRQ
2. Is it possible that the PCB has poor anti-interference ability (EMI), and whether there is a strong magnetic field or a component that is prone to inductive magnetic fields near the signal line.

Finally, the question will be closed as this has nothing to do with this library itself, it's a hardware issue.
